<?php
return[
    'db'=>[
        'host'=>'localhost',
        'name'=>'blog',
        'login'=>'root',
        'password'=>'',
        'charset'=>'utf8mb4',
        'collate'=>'utf8mb4_0900_ai_ci',
        'driver'=>'mysql'
    ]
]
?>
